# Generated by Django 6.0.6 on 2026-06-19 10:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_phone_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Phones'},
        ),
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
