# Generated by Django 5.2.15 on 2026-06-25 12:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_category_options_alter_phone_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='voice_note',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='voice'),
        ),
    ]
