# Generated by Django 5.2.15 on 2026-06-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_phone_voice_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='voice/'),
        ),
    ]
