# Generated by Django 5.2.15 on 2026-06-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_phone_voice_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='voice_note',
        ),
    ]
