# Generated by Django 5.2.15 on 2026-06-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_newsletter_order_alter_category_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='phone',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='color_options',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='features',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='views',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
